export { readDocument, writeDocument } from './document.js'
export { ReleaseManager } from './release.js'
export type { ReleaseSummary } from './release.js'
export { detectAgentFiles, trackAgentChanges, writeAgentLogEntry, readAgentLog } from './agent-tracker.js'
export type { AgentFile, AgentLogEntry, AgentChangeType, AgentChange } from './agent-tracker.js'
export { scanProject } from './scanner.js'
export type { ProjectIndex, ScanWarning } from './scanner.js'
export { ProjectRegistry } from './registry.js'
export type { RegistryProject } from './registry.js'
export { CurayeNotFoundError, RegistryError, DocumentWriteError, SharedLayerError } from './errors.js'
export { SharedLayer, SHARED_DIR, CATEGORIES } from './shared-layer.js'
export type { SharedDocument, SharedNotification, SharedCategory, PromoteInput, PromoteResult } from './shared-layer.js'
export { DriftDetector } from './drift-detector.js'
export type { DriftFinding, DriftReport, DriftClassification } from './drift-detector.js'
